djangotweet/djangotweet/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweetapp.urls')),
    path("", include("django.contrib.auth.urls")),
    
]

djangotweet/tweetapp/urls.py
from django.urls import path
from . import views

app_name = 'tweetapp'

urlpatterns = [
    path('add_tweet/', views.add_tweet, name='add_tweet'),
    path('', views.list_tweet, name='list_tweet'),
    path('add_tweetbyform/', views.add_tweetbyform, name='add_tweetbyform'),
    path('add_tweetbymodelform/', views.add_tweetbymodelform, name='add_tweetbymodelform'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('deletetweet/<int:id>/', views.deletetweet, name='deletetweet'),
    path('edit_tweet/<int:id>/', views.edit_tweet, name='edit_tweet')
]

djangotweet/tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tweet(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True)#kullanıcı silinince on_delete twitleri de silinir 
    tweet=models.CharField(max_length=140)
    #created_at=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Tweet User:{self.username}  Tweet: {self.tweet}"

djangotweet/tweetapp/forms.py
from django import forms
from django.forms import ModelForm
from tweetapp.models import Tweet

class AddTweetForm(forms.Form):
    nickname_input = forms.CharField(max_length=50, label='Your nickname')
    tweet_input = forms.CharField(max_length=140)
    
    
class AddTweetModelForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ['username', 'tweet'] 

djangotweet/tweetapp/views.py
from django.shortcuts import render,redirect
from . import models
from django.urls import reverse,reverse_lazy
from . import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView


# Create your views here.

@login_required(login_url="/login")
def add_tweet(request):
    if request.method == 'POST':
        tweet = request.POST["tweet"]
        models.Tweet.objects.create(username=request.user, tweet=tweet)
        return redirect(reverse('tweetapp:list_tweet'))
    else:
        return render(request, 'tweetapp/add_tweet.html')


def list_tweet(request):
    all_tweets = models.Tweet.objects.all()
    tweet_dict={'tweets':all_tweets} 
    return render(request, 'tweetapp/list_tweet.html', context=tweet_dict)

def add_tweetbyform(request):
    if request.method == 'POST':
        form = forms.AddTweetForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data['nickname_input']
            tweet = form.cleaned_data['tweet_input']
            new_tweet = models.Tweet(nickname=nickname, tweet=tweet)
            new_tweet.save()
            return redirect(reverse('tweetapp:list_tweet'))
    else:
        form = forms.AddTweetForm()
    return render(request, 'tweetapp/add_tweetbyform.html', {'form': form})

def add_tweetbymodelform(request):
    if request.method == 'POST':
        form = forms.AddTweetModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('tweetapp:list_tweet'))
    else:
        form = forms.AddTweetModelForm()
    return render(request, 'tweetapp/add_tweetbymodelform.html', {'form': form})

@login_required(login_url="/login")
def deletetweet(request, id):
    tweet = models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect(reverse('tweetapp:list_tweet'))
    
def edit_tweet(request, id):
    tweet = models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        if request.method == 'POST':
            tweet.tweet = request.POST['tweet']
            tweet.save()
            return redirect(reverse('tweetapp:list_tweet'))
        else:
            return render(request, 'tweetapp/edit_tweet.html', {'tweet': tweet})
   

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = 'registration/signup.html'
    
    
    
    
    
    

djangotweet/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Tweet App</title>
    <link rel="stylesheet" href="{% static 'tweetapp/customform.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Tweet App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'tweetapp:list_tweet'%}">List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tweetapp:add_tweet'%}">Add Tweet</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'tweetapp:add_tweetbymodelform'%}">Add Tweet by ModelForm</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'login'%}">Login</a>
                </li>
                <li>
                    <form method="post" action="{% url 'logout' %}?next=/">
                        {% csrf_token %}
                        <button type="submit" class="nav-link btn btn-link" >Logout</button>
                    </form>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'tweetapp:signup'%}">Signup</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


    {% block content %}

    {% endblock %}
</body>
</html>

djangotweet/tweetapp/templates/tweetapp/add_tweet.html
{% extends "base.html" %}
{% load static %}



{% block content %}
<div class="container tweetform">
    <h1>Add Tweet</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {% comment %} <div class="mb-3">
            <label for="nickname" class="form-label">Nickname</label>
            <input type="text" class="form-control" id="nickname" name="nickname">
        </div> {% endcomment %}
        <div class="mb-3">
            <label for="tweet" class="form-label">Tweet</label>
            <textarea class="form-control" id="tweet" name="tweet" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Send Tweet</button>
    </form>


{%  endblock %}

djangotweet/tweetapp/templates/tweetapp/add_tweetbyform.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Add Tweet by form</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Send Tweet</button>
    </form>


{%  endblock %}

djangotweet/tweetapp/templates/tweetapp/add_tweetbymodelform.html
{% extends "base.html" %}
{% load static %}



{% block content %}
<div class="container tweetform">
    <h1>Add Tweet</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="nickname" class="form-label">Nickname</label>
            <input type="text" class="form-control" id="nickname" name="nickname">
        <div class="mb-3">
            <label for="tweet" class="form-label">Tweet</label>
            <textarea class="form-control" id="tweet" name="tweet" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Send Tweet</button>
    </form>


{%  endblock %}

djangotweet/tweetapp/templates/tweetapp/edit_tweet.html
{% extends "base.html" %}
{% load static %}



{% block content %}

<div class="container tweetform">
    <h1>Edit Tweet</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="tweet" class="form-label">Tweet</label>
            <textarea class="form-control" id="tweet" name="tweet" rows="3">{{tweet.tweet}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Edit Tweet</button>
    </form>


{%  endblock %}

djangotweet/tweetapp/templates/tweetapp/list_tweet.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="tweetform" >
        {% for tweet in tweets %}
                <div class="card " style="padding:50px;">
                    <div class="card-header" style="background-color: brown;">
                        <h4>{{ tweet.username }}</h4>

                    </div>

                    <div class="card-body">
                        <p class="card-text">{{ tweet.tweet}}</p>

                    </div>
                    {%if tweet.username == user%}
                    <div class="card-footer">
                        <a href="{%url 'tweetapp:deletetweet' id=tweet.id  %}" class="btn btn-danger">Delete</a>
                        </div>
                    {%endif%}

                    {%if tweet.username == user%}
                    <div class="card-footer">
                        <a href="{%url 'tweetapp:edit_tweet' id=tweet.id  %}" class="btn btn-primary">Edit</a>
                        </div>
                    {%endif%}
                
                </div>
        {% endfor %}
    </div>


{%  endblock %}